-- Karman v2. Run once in a NEW Supabase project via SQL Editor.
create extension if not exists pgcrypto with schema extensions;
create schema if not exists private;
revoke all on schema private from public, anon, authenticated;

create table public.profiles (
 id uuid primary key references auth.users(id) on delete cascade,
 nickname text not null check(nickname ~ '^[a-z][a-z0-9_]{2,23}$'),
 nickname_key text generated always as (translate(replace(lower(nickname),'_',''),'01357','olest')) stored unique,
 display_name text not null default '' check(length(display_name)<=80),
 avatar_url text, last_seen timestamptz, created_at timestamptz default now() not null
);
create table private.accounts(id uuid primary key references auth.users(id) on delete cascade,email text not null);
create unique index accounts_email_unique on private.accounts(lower(email));
create table public.diary_settings(owner_id uuid primary key references public.profiles(id) on delete cascade,payload jsonb not null default '{"goal":50000}');
create table public.entries(id uuid primary key,owner_id uuid not null references public.profiles(id) on delete cascade,kind text not null check(kind in ('expense','saving','place')),payload jsonb not null,created_at timestamptz default now() not null,check(payload->>'kind'=kind),check(payload->>'id'=id::text));
create index entries_owner on public.entries(owner_id);
create table public.friendships(user_a uuid references public.profiles(id) on delete cascade,user_b uuid references public.profiles(id) on delete cascade,created_at timestamptz not null default now(),primary key(user_a,user_b),check(user_a<user_b));
create table private.invites(code_hash text primary key,owner_id uuid references public.profiles(id) on delete cascade,expires_at timestamptz not null,used_at timestamptz,created_at timestamptz not null default now());
create table public.messages(id uuid primary key default gen_random_uuid(),sender_id uuid not null references public.profiles(id) on delete cascade,recipient_id uuid not null references public.profiles(id) on delete cascade,body text not null default '' check(length(body)<=4000),media_path text,media_type text check(media_type in ('image','video')),read_at timestamptz,created_at timestamptz not null default now(),check(sender_id<>recipient_id),check(length(body)>0 or media_path is not null));
create index messages_conversation on public.messages(sender_id,recipient_id,created_at);
create table public.reminders(id uuid primary key,owner_id uuid not null references public.profiles(id) on delete cascade,created_by uuid not null references public.profiles(id) on delete cascade,payload jsonb not null,next_due timestamptz,enabled boolean not null default true,claim_id uuid,claim_until timestamptz,created_at timestamptz default now() not null,check(payload->>'id'=id::text));
create index reminders_due on public.reminders(next_due) where enabled;
create table public.push_subscriptions(id uuid primary key default gen_random_uuid(),owner_id uuid not null references public.profiles(id) on delete cascade,endpoint text not null unique,subscription jsonb not null,created_at timestamptz default now() not null);
create table private.outbox(id uuid primary key default gen_random_uuid(),owner_id uuid not null references public.profiles(id) on delete cascade,title text not null,body text not null,url text not null,tag text not null,created_at timestamptz not null default now(),delivered_at timestamptz,claim_id uuid,claim_until timestamptz);
create table private.admin_limits(key text primary key,hits integer not null default 1,window_at timestamptz not null default now());

create function public.are_friends(a uuid,b uuid) returns boolean language sql stable security definer set search_path='' as $$select auth.uid() is not null and auth.uid() in(a,b) and exists(select 1 from public.friendships where user_a=least(a,b) and user_b=greatest(a,b))$$;
-- 24-character nickname limit: UUID prefix is generated by the server.
create function public.new_account() returns trigger language plpgsql security definer set search_path='' as $$begin
 if new.raw_app_meta_data->>'provider' is distinct from 'google' or new.email is null then raise exception 'Google accounts only';end if;
 insert into private.accounts(id,email) values(new.id,lower(new.email));
 insert into public.profiles(id,nickname,display_name,avatar_url) values(new.id,'user_'||left(replace(new.id::text,'-',''),16),left(coalesce(new.raw_user_meta_data->>'full_name','Пользователь'),80),new.raw_user_meta_data->>'avatar_url');
 insert into public.diary_settings(owner_id) values(new.id);return new;end$$;
create trigger account_created after insert on auth.users for each row execute function public.new_account();
create function public.heartbeat() returns void language sql security definer set search_path='' as $$update public.profiles set last_seen=now() where id=auth.uid()$$;
create function public.create_invite() returns text language plpgsql security definer set search_path='' as $$declare code text;begin
 if auth.uid() is null then raise exception 'Sign in first';end if;
 if (select count(*) from private.invites where owner_id=auth.uid() and created_at>now()-interval '1 day')>=10 then raise exception 'Too many invitations';end if;
 update private.invites set expires_at=now() where owner_id=auth.uid() and used_at is null;
 code=upper(encode(extensions.gen_random_bytes(12),'hex'));
 insert into private.invites(code_hash,owner_id,expires_at,used_at) values(encode(extensions.digest(code,'sha256'),'hex'),auth.uid(),now()+interval '24 hours',null);return code;end$$;
create function public.join_friend(code text) returns uuid language plpgsql security definer set search_path='' as $$declare target uuid;begin
 if auth.uid() is null then raise exception 'Sign in first';end if;
 select owner_id into target from private.invites where code_hash=encode(extensions.digest(upper(regexp_replace(code,'\s','','g')),'sha256'),'hex') and used_at is null and expires_at>now() for update;
 if target is null then raise exception 'Invalid or expired invitation';end if;if target=auth.uid() then raise exception 'Own invitation';end if;
 insert into public.friendships(user_a,user_b) values(least(target,auth.uid()),greatest(target,auth.uid())) on conflict do nothing;
 update private.invites set used_at=now() where code_hash=encode(extensions.digest(upper(regexp_replace(code,'\s','','g')),'sha256'),'hex');return target;end$$;
create function public.remove_friend(target uuid) returns void language plpgsql security definer set search_path='' as $$begin
 delete from public.friendships where user_a=least(target,auth.uid()) and user_b=greatest(target,auth.uid());
 update public.reminders set enabled=false,payload=jsonb_set(payload,'{enabled}','false'::jsonb),next_due=null where (owner_id=auth.uid() and created_by=target) or (owner_id=target and created_by=auth.uid());end$$;
create function public.search_profiles(term text) returns table(id uuid,nickname text,display_name text,avatar_url text,last_seen timestamptz) language sql stable security definer set search_path='' as $$select p.id,p.nickname,p.display_name,p.avatar_url,p.last_seen from public.profiles p where auth.uid() is not null and length(term)>=3 and p.nickname like lower(term)||'%' and p.id<>auth.uid() order by p.nickname limit 20$$;
create function public.update_profile(nick text,display text) returns void language plpgsql security definer set search_path='' as $$begin
 if lower(nick) in ('admin','administrator','support','karman') then raise exception 'Reserved nickname';end if;
 update public.profiles set nickname=lower(nick),display_name=left(display,80) where id=auth.uid();end$$;

create function public.schedule_reminder() returns trigger language plpgsql security definer set search_path='' as $$declare stamp timestamp;begin
 if coalesce(length(new.payload->>'title'),0) not between 1 and 120 or length(coalesce(new.payload->>'body',''))>400 or coalesce(new.payload->>'repeat','') not in ('daily','once') or coalesce(new.payload->>'time','') !~ '^([01][0-9]|2[0-3]):[0-5][0-9]$' or coalesce(new.payload->>'date','') !~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}$' then raise exception 'Invalid reminder';end if;
 new.enabled=coalesce((new.payload->>'enabled')::boolean,true);
 if tg_op='UPDATE' then
 if new.payload->>'date'=old.payload->>'date' and new.payload->>'time'=old.payload->>'time' and new.payload->>'repeat'=old.payload->>'repeat' and new.enabled=old.enabled then return new;end if;end if;
 if not new.enabled then new.next_due=null;return new;end if;
 if new.payload->>'repeat'='daily' then stamp=(now() at time zone 'Asia/Bishkek')::date+(new.payload->>'time')::time; if stamp<now() at time zone 'Asia/Bishkek' or new.payload->>'fired'=to_char(now() at time zone 'Asia/Bishkek','YYYY-MM-DD') then stamp=stamp+interval '1 day';end if;
 else if new.payload->>'fired'=new.payload->>'date' then new.next_due=null;return new;end if;stamp=(new.payload->>'date')::date+(new.payload->>'time')::time;end if;
 new.next_due=stamp at time zone 'Asia/Bishkek';new.claim_id=null;new.claim_until=null;return new;end$$;
create trigger reminder_schedule before insert or update of payload on public.reminders for each row execute function public.schedule_reminder();
create function public.remind_friend(target uuid,title text,body text,day text,at_time text) returns uuid language plpgsql security definer set search_path='' as $$declare rid uuid=gen_random_uuid();begin
 if not public.are_friends(auth.uid(),target) then raise exception 'Friendship required';end if;
 if (day::date+at_time::time) at time zone 'Asia/Bishkek'<now() then raise exception 'Choose a future time';end if;
 if (select count(*) from public.reminders where created_by=auth.uid() and owner_id<>auth.uid() and created_at>now()-interval '1 day')>=20 then raise exception 'Daily reminder limit';end if;
 insert into public.reminders(id,owner_id,created_by,payload) values(rid,target,auth.uid(),jsonb_build_object('id',rid,'title',title,'body',body,'date',day,'time',at_time,'repeat','once','enabled',true,'fromFriend',auth.uid()));return rid;end$$;
create function public.mark_read(friend_id uuid) returns void language sql security definer set search_path='' as $$update public.messages set read_at=now() where recipient_id=auth.uid() and sender_id=friend_id and read_at is null$$;
create function public.queue_message() returns trigger language plpgsql security definer set search_path='' as $$declare nick text;begin
 select nickname into nick from public.profiles where id=new.sender_id;
 insert into private.outbox(owner_id,title,body,url,tag) values(new.recipient_id,'@'||nick,case when new.media_type='video' then 'Прислал видео' when new.media_type='image' then 'Прислал фото' else left(new.body,160) end,'/chats?friend='||new.sender_id,'message-'||new.id);return new;end$$;
create trigger message_push after insert on public.messages for each row execute function public.queue_message();
create function public.limit_message() returns trigger language plpgsql security definer set search_path='' as $$begin
 if (select count(*) from public.messages where sender_id=new.sender_id and created_at>now()-interval '1 minute')>=30 then raise exception 'Too many messages';end if;
 if new.media_path is not null and new.media_path not like new.sender_id::text||'/chat/%' then raise exception 'Invalid attachment';end if;return new;end$$;
create trigger message_limits before insert on public.messages for each row execute function public.limit_message();

alter table public.profiles enable row level security;
alter table public.diary_settings enable row level security;
alter table public.entries enable row level security;
alter table public.friendships enable row level security;
alter table public.messages enable row level security;
alter table public.reminders enable row level security;
alter table public.push_subscriptions enable row level security;
create policy profiles_visible on public.profiles for select to authenticated using(id=auth.uid() or public.are_friends(auth.uid(),id));
create policy settings_own on public.diary_settings for all to authenticated using(owner_id=auth.uid()) with check(owner_id=auth.uid());
create policy entries_read on public.entries for select to authenticated using(owner_id=auth.uid() or (kind='place' and coalesce(payload->>'shared','false')='true' and public.are_friends(auth.uid(),owner_id)));
create policy entries_insert on public.entries for insert to authenticated with check(owner_id=auth.uid());
create policy entries_update on public.entries for update to authenticated using(owner_id=auth.uid()) with check(owner_id=auth.uid());
create policy entries_delete on public.entries for delete to authenticated using(owner_id=auth.uid());
create policy friends_read on public.friendships for select to authenticated using(auth.uid() in(user_a,user_b));
create policy messages_read on public.messages for select to authenticated using(auth.uid() in(sender_id,recipient_id));
create policy messages_insert on public.messages for insert to authenticated with check(sender_id=auth.uid() and public.are_friends(sender_id,recipient_id) and read_at is null);
create policy reminders_read on public.reminders for select to authenticated using(owner_id=auth.uid());
create policy reminders_insert on public.reminders for insert to authenticated with check(owner_id=auth.uid() and created_by=auth.uid());
create policy reminders_update on public.reminders for update to authenticated using(owner_id=auth.uid()) with check(owner_id=auth.uid());
create policy reminders_delete on public.reminders for delete to authenticated using(owner_id=auth.uid());
-- subscriptions are managed only by authenticated Vercel API, not directly from the client.
grant select on public.profiles,public.friendships to authenticated;
grant select,insert,update,delete on public.entries,public.diary_settings,public.reminders to authenticated;
grant select,insert on public.messages to authenticated;
revoke update,insert,delete on public.profiles,public.friendships from authenticated,anon;
revoke all on public.push_subscriptions from anon,authenticated;
revoke all on all functions in schema public from public,anon;
grant execute on function public.are_friends(uuid,uuid),public.heartbeat(),public.create_invite(),public.join_friend(text),public.remove_friend(uuid),public.search_profiles(text),public.update_profile(text,text),public.remind_friend(uuid,text,text,text,text),public.mark_read(uuid) to authenticated;

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('media','media',false,52428800,array['image/jpeg','image/png','image/webp','image/gif','image/heic','audio/mpeg','audio/mp4','audio/wav','audio/x-wav','audio/ogg','audio/webm','video/mp4','video/webm','video/quicktime']) on conflict(id) do nothing;
create policy media_upload on storage.objects for insert to authenticated with check(bucket_id='media' and (storage.foldername(name))[1]=auth.uid()::text);
create policy media_own_delete on storage.objects for delete to authenticated using(bucket_id='media' and (storage.foldername(name))[1]=auth.uid()::text);
create policy media_read on storage.objects for select to authenticated using(bucket_id='media' and (
 (storage.foldername(name))[1]=auth.uid()::text or
 exists(select 1 from public.entries e where e.kind='place' and e.payload->>'photo'='cloud:'||name and e.payload->>'shared'='true' and public.are_friends(auth.uid(),e.owner_id)) or
 exists(select 1 from public.messages m where m.media_path=name and auth.uid() in(m.sender_id,m.recipient_id))
));
alter publication supabase_realtime add table public.messages,public.reminders,public.entries,public.friendships;

-- Service-only APIs: private data never exposed to ordinary clients.
create function public.admin_rate(key_hash text) returns integer language plpgsql security definer set search_path='' as $$declare n integer;begin
 insert into private.admin_limits(key) values(key_hash) on conflict(key) do update set hits=case when private.admin_limits.window_at<now()-interval '15 minutes' then 1 else private.admin_limits.hits+1 end,window_at=case when private.admin_limits.window_at<now()-interval '15 minutes' then now() else private.admin_limits.window_at end returning hits into n;return n;end$$;
create function public.admin_users() returns table(id uuid,email text,nickname text,display_name text,avatar_url text,last_seen timestamptz,created_at timestamptz,photos bigint) language sql security definer set search_path='' as $$select p.id,a.email,p.nickname,p.display_name,p.avatar_url,p.last_seen,p.created_at,(select count(*) from public.entries e where e.owner_id=p.id and e.payload->>'photo' is not null) from public.profiles p join private.accounts a on a.id=p.id order by p.created_at desc limit 1000$$;
create function public.claim_notifications(worker uuid) returns jsonb language plpgsql security definer set search_path='' as $$declare rs jsonb;ms jsonb;begin
 with picked as (select id from public.reminders where enabled and next_due<=now() and (claim_until is null or claim_until<now()) order by next_due for update skip locked limit 100),claimed as(update public.reminders r set claim_id=worker,claim_until=now()+interval '5 minutes' from picked where r.id=picked.id returning r.*)select coalesce(jsonb_agg(to_jsonb(claimed)),'[]') into rs from claimed;
 with picked as(select id from private.outbox where delivered_at is null and (claim_until is null or claim_until<now()) order by created_at for update skip locked limit 100),claimed as(update private.outbox o set claim_id=worker,claim_until=now()+interval '5 minutes' from picked where o.id=picked.id returning o.*)select coalesce(jsonb_agg(to_jsonb(claimed)),'[]') into ms from claimed;
 return jsonb_build_object('reminders',rs,'messages',ms);end$$;
create function public.complete_notification(worker uuid,item uuid,kind text) returns void language plpgsql security definer set search_path='' as $$begin
 if kind='message' then update private.outbox set delivered_at=now(),claim_until=null where id=item and claim_id=worker;
 else update public.reminders set next_due=case when payload->>'repeat'='daily' then ((now() at time zone 'Asia/Bishkek')::date+1+(payload->>'time')::time) at time zone 'Asia/Bishkek' else null end,enabled=case when payload->>'repeat'='daily' then true else false end,payload=jsonb_set(jsonb_set(payload,'{fired}',to_jsonb(to_char(next_due at time zone 'Asia/Bishkek','YYYY-MM-DD'))),'{enabled}',to_jsonb(payload->>'repeat'='daily')),claim_until=null where id=item and claim_id=worker;end if;end$$;
revoke all on function public.admin_rate(text),public.admin_users(),public.claim_notifications(uuid),public.complete_notification(uuid,uuid,text) from public,anon,authenticated;
grant execute on function public.admin_rate(text),public.admin_users(),public.claim_notifications(uuid),public.complete_notification(uuid,uuid,text) to service_role;
-- Atomically apply a diary change; a failed statement rolls everything back.
create function public.save_diary_delta(changed_entries jsonb,deleted_entries uuid[],changed_reminders jsonb,deleted_reminders uuid[],settings_payload jsonb) returns void language plpgsql security invoker set search_path='' as $$declare r jsonb;begin
 if auth.uid() is null then raise exception 'Sign in first';end if;
 if jsonb_array_length(changed_entries)>10000 or jsonb_array_length(changed_reminders)>1000 then raise exception 'Too many records';end if;
 delete from public.entries where owner_id=auth.uid() and id=any(deleted_entries);
 for r in select value from jsonb_array_elements(changed_entries) loop
 insert into public.entries(id,owner_id,kind,payload) values((r->>'id')::uuid,auth.uid(),r->>'kind',r) on conflict(id) do update set payload=excluded.payload,kind=excluded.kind;end loop;
 delete from public.reminders where owner_id=auth.uid() and id=any(deleted_reminders);
 for r in select value from jsonb_array_elements(changed_reminders) loop
 if exists(select 1 from public.reminders where id=(r->>'id')::uuid and owner_id=auth.uid()) then update public.reminders set payload=r where id=(r->>'id')::uuid and owner_id=auth.uid();
 else insert into public.reminders(id,owner_id,created_by,payload) values((r->>'id')::uuid,auth.uid(),auth.uid(),r);end if;end loop;
 if settings_payload is not null then
 if not(settings_payload->>'goal' ~ '^[0-9]+(\.[0-9]+)?$') or (settings_payload->>'goal')::numeric<=0 then raise exception 'Invalid goal';end if;
 insert into public.diary_settings(owner_id,payload) values(auth.uid(),settings_payload) on conflict(owner_id) do update set payload=excluded.payload;end if;end$$;
revoke update on public.reminders from authenticated;grant update(payload) on public.reminders to authenticated;
revoke insert on public.messages from authenticated;
grant insert(id,sender_id,recipient_id,body,media_path,media_type) on public.messages to authenticated;
revoke all on function public.save_diary_delta(jsonb,uuid[],jsonb,uuid[],jsonb) from public,anon;
grant execute on function public.save_diary_delta(jsonb,uuid[],jsonb,uuid[],jsonb) to authenticated;
create function public.claim_message(worker uuid,msg uuid) returns jsonb language plpgsql security definer set search_path='' as $$declare result jsonb;begin
 update private.outbox set claim_id=worker,claim_until=now()+interval '5 minutes' where tag='message-'||msg and delivered_at is null and (claim_until is null or claim_until<now()) returning to_jsonb(private.outbox.*) into result;return result;end$$;
revoke all on function public.claim_message(uuid,uuid) from public,anon,authenticated;grant execute on function public.claim_message(uuid,uuid) to service_role;

create function public.sync_account_email() returns trigger language plpgsql security definer set search_path='' as $$begin update private.accounts set email=lower(new.email) where id=new.id;return new;end$$;
create trigger account_email_updated after update of email on auth.users for each row execute function public.sync_account_email();
revoke all on function public.sync_account_email() from public,anon,authenticated;
-- Media references must belong to the row owner; shared posts cannot launder foreign files.
alter table public.entries add constraint entry_photo_owner check(payload->>'photo' is null or payload->>'photo' like 'cloud:'||owner_id::text||'/diary/%');
alter table public.entries add constraint entry_valid_amount check(jsonb_typeof(payload->'amount')='number' and (payload->>'amount')::numeric>=0 and (kind='place' or (payload->>'amount')::numeric>0));
alter table public.entries add constraint entry_title check(payload->>'title' is not null and length(payload->>'title') between 1 and 180);
alter table public.reminders add constraint reminder_sound_owner check(payload->>'sound' is null or payload->>'sound' like 'cloud:'||owner_id::text||'/diary/%');
create index outbox_pending on private.outbox(created_at) where delivered_at is null;
create index profile_recent_activity on public.profiles(last_seen);
create function public.admin_stats() returns jsonb language sql security definer set search_path='' as $$select jsonb_build_object('total',(select count(*) from public.profiles),'online',(select count(*) from public.profiles where last_seen>now()-interval '75 seconds'),'photos',(select count(*) from public.entries where payload->>'photo' is not null))$$;
revoke all on function public.admin_stats() from public,anon,authenticated;grant execute on function public.admin_stats() to service_role;
-- Prevent a single substituted, inserted or removed character in a claimed nickname.
create function public.nickname_near(a text,b text) returns boolean language plpgsql immutable set search_path='' as $$declare i integer=1;j integer=1;diff integer=0;tmp text;begin
 if abs(length(a)-length(b))>1 then return false;end if;
 if length(a)>length(b) then tmp=a;a=b;b=tmp;end if;
 while i<=length(a) and j<=length(b) loop
 if substr(a,i,1)=substr(b,j,1) then i=i+1;j=j+1;
 else diff=diff+1;if diff>1 then return false;end if;if length(a)=length(b) then i=i+1;end if;j=j+1;end if;end loop;
 return diff+(length(a)-i+1)+(length(b)-j+1)<=1;end$$;
create or replace function public.update_profile(nick text,display text) returns void language plpgsql security definer set search_path='' as $$declare canonical text;begin
 if auth.uid() is null then raise exception 'Sign in first';end if;
 nick=lower(nick);canonical=translate(replace(nick,'_',''),'01357','olest');
 if nick in ('admin','administrator','support','karman') then raise exception 'Reserved nickname';end if;
 perform pg_advisory_xact_lock(867530911);
 if exists(select 1 from public.profiles p where p.id<>auth.uid() and public.nickname_near(canonical,p.nickname_key)) then raise exception 'This nickname or a similar one is taken' using errcode='23505';end if;
 update public.profiles set nickname=nick,display_name=left(display,80) where id=auth.uid();end$$;
revoke all on function public.nickname_near(text,text) from public,anon,authenticated;
revoke all on function public.update_profile(text,text) from public,anon;grant execute on function public.update_profile(text,text) to authenticated;
grant all on public.profiles,public.entries,public.reminders,public.messages,public.push_subscriptions,public.diary_settings,public.friendships to service_role;

create function public.protect_push_owner() returns trigger language plpgsql set search_path='' as $$begin if new.owner_id is distinct from old.owner_id then raise exception 'Push subscription belongs to another account';end if;return new;end$$;
create trigger subscription_owner_immutable before update of owner_id on public.push_subscriptions for each row execute function public.protect_push_owner();
revoke all on function public.protect_push_owner() from public,anon,authenticated;
